event:
  search:
    re: "Pineo( - (?P<type>(\\w+\\s+)+)(\\((?P<assigned_person>\\w+)\\))?)?"
    type_group: type
    assigned_person_group: assigned_person
  # Types should be in lower case and ascii characters
  types:
    - tic
    - genero
    - salud
    - inclusion social
    - institucional
    - medioambiente
    - taller participacion
    - cooperacion internacional
    - taller de habilidades sociales
